server:
  port: ${PORT:8761}

eureka:
  server:
    renewalPercentThreshold: 0.0
    enableSelfPreservation: false
    waitTimeInMsWhenSyncEmpty: 0
  client:
    registerWithEureka: true
    fetchRegistry: false
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadataMap:
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    registryFetchIntervalSeconds: 30
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationDurationInSeconds: 5

